### ISSUE TITLE
how does autoloading work?

### ISSUE THREAD

**Issue by craigh** [mmoreram/symfony-bundle-dependencies#6]
Since there is no integration with composer here, are we left to manually add the autoloading for the bundles added by this lib?

(sorry to put a support request in a ticket).

**Comment by mmoreram** [comment]
Composer is only required for resolving package dependencies. Only for ensuring the existence of the package in  vendor folder.

This library resolves that, if one bundle is instanced, then some other bundles **must** be instanced as well.

Each project covers part of this dependency requirement.

**Comment by craigh** [comment]
maybe I do not understand :confused: Composer creates an autoloader for bundles that are part of the main composer.json file. This is then included in my bootstrap, e.g. `$loader = require __DIR__.'/../app/autoload.php';`

this file will only include bundles identified in the main composer file. If my bundles have separate composer files, how do I add these "sub" autoloader files? manually?

**Comment by mmoreram** [comment]
Forget about composer.
Composer still works as always has.
This library only makes this:
- Bundle A requires B to work
- Since now, in Kernel you make `new A(); new B();`
- Because A requires B, you should be able to only instance A without B in your Kernel
- Then A requires B in a hard way (in composer as well, but composer only loads the code, doesn't instance anything)
- This interface allow you to add this dependency, `new A()` implies `new B()`

That's it :)
